{% set version = "21.0.1" %}

package:
  name: pip
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pip/pip-{{ version }}.tar.gz
  sha256: 99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5

build:
  noarch: python
  number: 0
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - setuptools
    - wheel

test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip

about:
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  doc_url: https://pip.pypa.io/en/stable/
  dev_url: https://github.com/pypa/pip

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
    - mingwandroid
