{% set version = "24.1" %}

package:
  name: pip
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pip/pip-{{ version }}.tar.gz
  sha256: bdae551038c0ce6a83030b4aedef27fc95f0daa683593fea22fa05e55ed8e317

build:
  noarch: python
  number: 0
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main

requirements:
  host:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - wheel

test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip

about:
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  doc_url: https://pip.pypa.io/en/stable/
  dev_url: https://github.com/pypa/pip

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
    - mingwandroid
